### ISSUE TITLE
SmoteRegress "All the points have relevance 0"

### ISSUE THREAD

**Issue by zym604** [paobranco/UBL#6]
The [example code](https://rdrr.io/cran/UBL/man/smoteRegress.html) doesn't work if you change the target from **Sepal.Width** to any other variables. For example, change to **Sepal.Length**:
```
smoteBalan.iris <- SmoteRegress(Sepal.Length~., ir, dist = "HEOM",
                                C.perc = "balance")
```
It returns:
```
>   smoteBalan.iris <- SmoteRegress(Sepal.Length~., ir, dist = "HEOM",
+                                 C.perc = "balance")
Error in SmoteRegress(Sepal.Length ~ ., ir, dist = "HEOM", C.perc = "balance") : 
  All the points have relevance 0. 
         Please, redefine your relevance function!
Execution halted
```
I think maybe it is a problem of the probability distribution? Because **Sepal.Length** is the only variable that looks continuous in the whole domain:
![image](https://user-images.githubusercontent.com/9557009/61061532-6aadb100-a3ca-11e9-8c35-7b3d0ac9be5d.png)
![image](https://user-images.githubusercontent.com/9557009/61061561-77320980-a3ca-11e9-9784-aa368eff74e6.png)
![image](https://user-images.githubusercontent.com/9557009/61061589-7f8a4480-a3ca-11e9-98a4-f658fa6d6f4b.png)
![image](https://user-images.githubusercontent.com/9557009/61061598-83b66200-a3ca-11e9-85b3-06d5d2cd1db7.png)
 
But I'm not sure what exactly happens. Please give me some hint.

**Comment by paobranco** [comment]
Hi,

The problem is related with the relevance function.
The resampling methods implemented use a relevance function that provides information regarding which are the important and unimportant values of the target variable.
This will allow the resampling methods to know where they will apply oversampling and undersampling.

The relevance function assigns a higher score (near 1) to the most important values and a lower score (near zero) to the less interesting values of the target variable.

In UBL package we use as default an automatic method for estimating the relevance function. This automatic method has assumptions regarding, for instance, the location of the important values (they are expected to be in the extremes of the target variable distribution).

However, some times, the automatic method provides a constant relevance, i.e., assigns to all values the same relevance/importance. In your error, all values were assigned a relevance of zero in this automatic method.

But the resampling methods need to differentiate between important and unimportant cases and this is impossible with a constant relevance. This is why the message also asks you to redefine the relevance function.

There are alternatives to the automatic method in UBL package. For instance, you can provide your own relevance function through a 3-column matrix. The [example code](https://rdrr.io/cran/UBL/man/smoteRegress.html) that you mention also has an example with  a user defined relevance function.

Essentially, it works as follows:
- the matrix needs to have 3 columns and can have as many rows as you wish;
- the first column represents the target variable value, the second the relevance score assigned and the third the derivative of the relevance function in that point.

For example, the row (2,1,0) means that for the target variable value of 2 we will assign a relevance score of 1 and the relevance function derivative will be zero.

You can find more about the relevance function [here](https://rdrr.io/cran/UBL/man/phi.html), [here](https://rdrr.io/cran/UBL/man/phiControl.html), [here](http://www.dcc.fc.up.pt/~rpribeiro/uba/) and [here](http://www.dcc.fc.up.pt/~rpribeiro/publ/rpribeiroPhD11.pdf).

Let me know if you have any doubts.
Thank you for your interest in UBL package!

**Comment by zym604** [comment]
Thank you @paobranco !

I have read the [PhD thesis](http://www.dcc.fc.up.pt/~rpribeiro/publ/rpribeiroPhD11.pdf) of Dr. Rita P. Ribeiro, but didn't understood how to implement my own relevance function. Your reply helps a lot!

But I still have some questions:
1. **Is the current SMOTER only work when the target variable is nearly normal distributed?** 
I ask this because of the following statement from Dr. Ribeiro's thesis:
![image](https://user-images.githubusercontent.com/9557009/61170367-11fb2700-a536-11e9-8f8b-9e5da8c3dd9f.png)
So maybe that's the reason why **Sepal.Width** is the only target variables that could be implemented, as other variables are not normally distributed. Am I right?

2. **What is the mathematical form of the automatic function?** 
It is stated in a [paper](https://researchcommons.waikato.ac.nz/bitstream/handle/10289/8518/smoteR.pdf?sequence=23&isAllowed=y) that the function is inversely proportional to the target variable pdf. 
![image](https://user-images.githubusercontent.com/9557009/61170467-69e65d80-a537-11e9-9196-384664daa47e.png)
But I think the real function should be a little different right? Otherwise, it couldn't explain the "all zero" error. 
I tried to check the function by searching it in the code. But it seems that the function is written in a Fortran object file, which I couldn't open. So the only thing I can do is ask you directly the math form.
![image](https://user-images.githubusercontent.com/9557009/61170507-20e2d900-a538-11e9-9aec-fc3b97e1dadb.png)

3. **Doesn't current SMOTER support window platform?**
I tried to install UBL on windows, but I failed because of some gcc stuff. 

Anyway, thank you and your group for making such a contribution!

**Comment by IrisOren** [comment]
Hi, I was having gcc error issues installing SMOTER on windows.

I finally got it installed by first installing Rtools on C: (https://cran.r-project.org/bin/windows/Rtools/), and then within R, install.packages("devtools"). After that, the smoteR could be built and installed.

Maybe this will help you?

**Comment by rpribeiro** [comment]
First of all, thank you for your interest in UBL and on the relevance function phi, in particular.

The automatic method for obtaining the relevance is based on the assumption that the most important values are the ones considered as outliers by the boxplot. It is based on this premise that we say that "that the function is inversely proportional to the target variable pdf". So, this is true considering that our focus is on rare extreme values and that they exist. Thus, it assumes a normal distribution for the continuous variable and uses the following points to interpolate and obtain the respective relevance function.  The median has relevance 0, the upper and lower whiskers have relevance 1, given that there are outliers.

So, in your case, if you do

> y <- iris$Sepal.Length
> phiF.args1 <- phi.control(y,method="extremes",extr.type="both")
> y.phi1 <- phi(y, control.parms=phiF.args1)
> plot(y, y.phi1)

you get a constant value function because there are no outliers according to the boxplot.

> boxplot.stats(y)

$stats
[1] 4.3 5.1 5.8 6.4 7.9

$n
[1] 150

$conf
[1] 5.632292 5.967708

$out
numeric(0)


From that perspective, the automatic method assumes that nothing is relevant. (We will probably change that.)

Anyway, you can still force the relevance function to interpolate the values you wish.

> s <- boxplot.stats(y)$stats
> rel <- matrix(0, ncol = 3, nrow = 0)
> rel <- rbind(rel, c(s[1], 1, 0))
> rel <- rbind(rel, c(s[3], 0, 0))
> rel <- rbind(rel, c(s[5], 1, 0))

> phiF.args2 <- phi.control(y,method="range",control.pts=rel)
> y.phi2 <- phi(y, control.parms=phiF.args2)
> plot(y,y.phi2)


I hope my answer has helped you in clarifying your issue.
Contact me, if you still have doubts.

Best regards,
Rita

**Comment by luna57-lr** [comment]
Thank you for your reply! I also met the same problem that"Error in RandOverRegress(RPA ~ ., datai, C.perc = "balance") : All the points have relevance 1. Please, redefine your relevance function!'
How should i define the relevance function ? My boxplot.stats(datai$RPA)$stats are all 0!
